# Generated by Django 5.0.3 on 2024-04-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='executiontwo',
            field=models.TextField(default='ffefe'),
            preserve_default=False,
        ),
    ]
