# Generated by Django 5.0.3 on 2024-04-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0002_cliente_executiontwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='opcao',
            field=models.CharField(choices=[('0', 'Serviço'), ('1', 'Diagnóstico'), ('2', 'Compra')], default='0', max_length=11),
        ),
    ]
