# Generated by Django 5.0.3 on 2024-04-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0003_alter_cliente_opcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='opcao',
            field=models.CharField(choices=[('1', 'Diagnóstico'), ('2', 'Compra'), ('0', 'Serviço')], default='0', max_length=11),
        ),
    ]
