# Generated by Django 5.0.3 on 2024-04-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0006_alter_cliente_date_alter_cliente_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='description',
            new_name='defect',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='execution',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='executiontwo',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='opcao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='option',
            field=models.CharField(choices=[('1', 'Diagnóstico'), ('2', 'Compra'), ('0', 'Serviço')], default='0', max_length=11),
        ),
    ]
