# Generated by Django 5.0.3 on 2024-04-15 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0007_rename_description_cliente_defect_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='option',
            field=models.CharField(choices=[('0', 'Serviço'), ('1', 'Diagnóstico'), ('2', 'Compra')], default='0', max_length=11),
        ),
    ]
