# Generated by Django 5.0.3 on 2024-04-25 17:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0008_cliente_user_alter_cliente_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='additional',
            field=models.TextField(default='(92) 992102282'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='ok', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
