# Generated by Django 5.0.3 on 2024-04-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0009_cliente_additional_cliente_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='option',
            field=models.CharField(choices=[('2', 'Compra'), ('1', 'Diagnóstico'), ('0', 'Serviço')], default='0', max_length=11),
        ),
    ]
