# Generated by Django 5.0.3 on 2024-04-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0010_alter_cliente_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='payment',
            field=models.CharField(default='a vista', max_length=100),
            preserve_default=False,
        ),
    ]
